spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/code_generate?useUnicode=true&characterEncoding=utf8&
    username: root
    password: 321321321
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 5000
    password:
    lettuce:
      pool:
        max-wait: 100
        max-active: 200   #连接池的最大连接数
        max-idle: 10  #最大空闲数
        min-idle: -1 #初始化连接数

